### ISSUE TITLE
value > is not a member of org.scalarules.engine.SingularFact[Int]

### ISSUE THREAD

**Issue by robin1988** [scala-rules/rule-viewer#8]
```
class MyBerekening extends Berekening(
  nl.grammar.Gegeven (factA > 0) Bereken factC is factB - factA
)
```

I am using the example mentioned in wiki but i get following error 

> value > is not a member of org.scalarules.engine.SingularFact[Int]

The above issue is in 0.3.4

and in 0.2.6 i get error in MyGlossary 

> missing arguments for method defineFact in class Glossary;
> follow this method with `_' if you want to treat it as a partially applied function

**Comment by vzorge** [comment]
Hey Robin.

You need to ensure that you have the proper imports, because we work with a lot of implicits, which need to be imported. You can try it with 
`
import org.scalarules.dsl.nl.grammar._
import MyGlossary._
`

See the main repository for more details (This is the viewer repo you are putting this issue on). Perhaps we have not documented things clearly enough, we will check out the documentation if it is clear enough about imports.

**Comment by NRBPerdijk** [comment]
Incomplete instructions are exactly the kind of problem that is difficult to spot by ourselves, so thanks for reporting the issue!

We have updated the readme in order to clarify the necessary imports:
https://github.com/scala-rules/examples

**Comment by NRBPerdijk** [comment]
Closing issue: no further feedback is positive feedback!
